const productsApi = [
    {
        id: "1",
        title: "Vestido liso",
        description: "Secure a signature look by showcasing this luxury comforter set from Madison Park",
        category: "vestidos",
        categoryId: "1",
        image: "/images/1db893b9-5622-44b5-a0e1-ad51bddf3259.jpg",
        price: 5,
        stock: 10,
    },
    {
        id: "2",
        title: "Falda nudo",
        description: "Secure a signature look by showcasing this luxury comforter set from Madison Park",
        category: "blusas",
        categoryId: "2",
        image: "/images/photo-2022-06-09-11-04-03_6.jpg",
        price: 15,
        stock: 3,
    },
    {
        id: "3",
        title: "Blusa broche centro",
        description: "Secure a signature look by showcasing this luxury comforter set from Madison Park",
        category: "camisetas",
        categoryId: "3",
        image: "/images/photo-2022-06-14-11-31-13_3.jpg",
        price: 25,
        stock: 7,
    },
    {
        id: "4",
        title: "Vestido flores",
        description: "Secure a signature look by showcasing this luxury comforter set from Madison Park",
        category: "pantalones",
        categoryId: "4",
        image: "/images/photo-2022-06-17-16-16-24_2.jpg",
        price: 105,
        stock: 6,
    },
    {
        id: "5",
        title: "Vestido flores",
        description: "Secure a signature look by showcasing this luxury comforter set from Madison Park",
        category: "vestidos",
        categoryId: "2",
        image: "/images/photo-2022-06-17-16-16-24_2.jpg",
        price: 105,
        stock: 6,
    },
]

export default productsApi;