const productsApi = [
    {
        id: "1",
        title: "Pantalón Cortp Lazo",
        description: "Secure a signature look by showcasing this luxury comforter set from Madison Park",
        category: "pantalones",
        categoryId: "1",
        image: "/images/springfield/Archivo_0.jpg",
        price: 5,
        stock: 10,
    },
    {
        id: "2",
        title: "Blusa Volante Hombro",
        description: "Secure a signature look by showcasing this luxury comforter set from Madison Park",
        category: "blusas",
        categoryId: "2",
        image: "/images/springfield/Archivo_1.jpg",
        price: 15,
        stock: 3,
    },
    {
        id: "3",
        title: "Blusa Volante Hombro",
        description: "Secure a signature look by showcasing this luxury comforter set from Madison Park",
        category: "blusas",
        categoryId: "3",
        image: "/images/springfield/Archivo_2.jpg",
        price: 25,
        stock: 7,
    },
    {
        id: "4",
        title: "Blusa Bordado Suizo",
        description: "Secure a signature look by showcasing this luxury comforter set from Madison Park",
        category: "blusas",
        categoryId: "4",
        image: "/images/springfield/Archivo_3.jpg",
        price: 105,
        stock: 6,
    },
    {
        id: "5",
        title: "Kimono Estampado Étnico",
        description: "Secure a signature look by showcasing this luxury comforter set from Madison Park",
        category: "pantalones",
        categoryId: "2",
        image: "/images/springfield/Archivo_9.jpg",
        price: 105,
        stock: 6,
    },
    {
        id: "6",
        title: "Vestido Midi Lazos",
        description: "Secure a signature look by showcasing this luxury comforter set from Madison Park",
        category: "vestidos",
        categoryId: "2",
        image: "/images/springfield/Archivo_8.jpg",
        price: 105,
        stock: 6,
    },
    {
        id: "7",
        title: "Camiseta motivo floral",
        description: "Secure a signature look by showcasing this luxury comforter set from Madison Park",
        category: "camisetas",
        categoryId: "2",
        image: "/images/springfield/Archivo_12.jpg",
        price: 105,
        stock: 6,
    },
]

export default productsApi;